### ISSUE TITLE
Consider having a service:list command

### ISSUE THREAD

**Issue by carlos-algms** [kgalli/cliw#74]
It would be useful to have a command like:

`cliw service:list` 

to know all available services that can be started/stopped within the active project.

I know about the `cliw service:status`, but I think it will not list services that never started.

**Comment by kgalli** [comment]
@carlos-algms as this is reasonable to have and super simple to add I created a PR right away. Somehow missed this issue in the past. Next time you can just ping me again if you do not get any response.
