### ISSUE TITLE
Consider db:restore for dumps in plain format

### ISSUE THREAD

**Issue by jenni** [kgalli/cliw#75]
`db:restore` fails when using a dump file in plain format.

It's currently failing with:
```
pg_restore: error: did not find magic string in file header
```

More info can be found here:
https://dba.stackexchange.com/a/111910/205867

**Comment by kgalli** [comment]
If you have a `pg_dump` in plain format you would simply use `cliw db:console --file <you-file-with-plain-sql-statements>`. So there is absolutely no need for a change.

**Comment by kgalli** [comment]
See:  `cliw db:console --help`

The `-f` (`--file`) option to be even more precise.

```
run database console

USAGE
  $ cliw db:console DATASOURCE

ARGUMENTS
  DATASOURCE  (api) data source specified by name

OPTIONS
  -c, --command=command               run only single command (SQL or internal) and exit
  -e, --environment=development|test  (required) [default: development]
  -f, --file=file                     execute commands from file, then exit
  -h, --help                          show CLI help
  --dry-run                           print shell commands without executing
```
